### ISSUE TITLE
Migrations do not support environments

### ISSUE THREAD

**Issue by kenjis** [fuel/core#901] opened 2012-04-03 10:04 UTC
Current Migrations only updates "core/config/migrations.php" or "app/config/migrations.php" and does not support Environments.

But developers may use one installation as both development and test environments.

See: http://fuelphp.com/forums/topics/view/8566

**Comment by rob-mccann** [comment] 2012-04-03 14:07
Do you mean this:

`php oil r migrate --env=production` ?

**Comment by WanWizard** [comment] 2012-04-03 15:45
No, the problem is that the state of the migration is written to the config file app/config/migrations.php. Which means your application can only have one state.

If you want to support multiple environments within a single application installation, this file needs to be in the environment folder, not in the main folder.

**Comment by kenjis** [comment] 2012-04-03 21:19
And `env FUEL_ENV test php oil r migrate` reads "config/test/migrations.php", but writes the state to "config/migrations.php"

**Comment by kenjis** [comment] 2012-05-07 11:21
fixed https://github.com/fuel/core/commit/3c92f7c975807afb6065901fb8b48fa269c13cd9

**Comment by WanWizard** [comment] 2012-05-07 15:15
Indeed. Forgot to close this one.

**Closed as completed by WanWizard** 2012-05-07 15:15 UTC
Labels: Feature, Pending
