### ISSUE TITLE
Error View(s)

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#299] opened 2011-07-22 15:04 UTC
When core/views/errors/php_error.php is used to display an error, it shows the erroneous code. If this code is on the last line of the file, a "Notice: Undefined offset: 4" error is created. 

This may be the case in other error views also. 

It's likely a fairly simple fix - sorry I don't currently have the time to do it.

**Comment by dhrrgn** [comment] 2011-07-26 00:29
I can't reproduce this on the develop branch.  Can you post the code to reproduce the error?

Thanks.

**Comment by phil-lavin** [comment] 2011-07-26 07:43
Controller as such..

app/classes/controller/foo.php:

``` php
<?php
class Controller_Foo extends Controller {
    public function action_bar() {
        $this->response->body = View::factory('foo');
    }
}
```

View as such...

app/views/foo.php:

``` php
<?php
echo $titsonafish;
```

Error as follows...

Notice!

ErrorException [ Notice ]: Undefined variable: titsonafish

APPPATH/views/foo.php @ line 2:
1:  <?php
2:  echo $titsonafish;

( ! ) Notice: Undefined offset: 3 in /mnt/pdrive/Clients/richardjames.co.uk/versions/phil/includes/fuel/core/views/errors/php_error.php on line 9

**Comment by Savageman** [comment] 2011-07-26 08:13
I happens when a view has a variable, but the controller didn't defined it. So basically the var is undefined, throwing an PP notice.

**Comment by phil-lavin** [comment] 2011-07-26 08:14
That isn't really the issue. One would expect the "ErrorException [ Notice ]: Undefined variable: titsonafish" but not the "( ! ) Notice: Undefined offset: 3 in /mnt/pdrive/Clients/richardjames.co.uk/versions/phil/includes/fuel/core/views/errors/php_error.php on line 9"

**Comment by dhrrgn** [comment] 2011-07-26 11:00
Just tested this and it does not happen on the latest develop branch.  What version are you running?

**Comment by dhrrgn** [comment] 2011-07-28 12:29
I have tried reproducing this many times with the provided code as well as with some really crappy code i purposefully wrote myself, and I am unable to make this happen.  Closing the issue.

**Closed as completed by dhrrgn** 2011-07-28 12:29 UTC
Labels: Invalid
