### ISSUE TITLE
Redis: Unknown Response

### ISSUE THREAD

**Issue by andreoav** [fuel/core#1243] opened 2012-12-14 20:56 UTC
Hi, I'm trying to build an email sender worker using a task that will fetch data from a redis list using the command BLPOP.

The code works, but after some minutes the woker closes with a RedisException

**Unknown Response**

The problem is not with redis-server timeout, if I use this in the terminal it works without error.
Also, it's not a php script timeout, I got the same result using Pagodabox workers that does not timeout.

Can you help me solving this?

**Comment by andreoav** [comment] 2012-12-14 21:15
After some more tests, and a log. The error is exactly 1 minute after I start the worker. The "[Mailer] Redis error" part is add by me in the log.

```
Warning - 2012-12-14 19:10:42 --> Fuel\Core\Fuel::init - The configured locale pt_BR is not installed on your system.
Error - 2012-12-14 19:11:42 --> [Mailer] Redis error: Unknown response: 
Warning - 2012-12-14 19:12:03 --> Fuel\Core\Fuel::init - The configured locale pt_BR is not installed on your system.
Error - 2012-12-14 19:13:03 --> [Mailer] Redis error: Unknown response: 
```

**Comment by WanWizard** [comment] 2012-12-15 14:36
This exception means that Redis gave an invalid response back. From the log message I can't see if the response was blank, CRLF or some unprintable character.

In any case, it's invalid according to the specs: https://redis-docs.readthedocs.org/en/latest/ProtocolSpecification.html

There is an outstanding bug (in Redis) that this can happen with certain commands in combination with stack-type operations. Not really something we can do anything about. 

As a workaround you could try using a try/catch block, catch the exception, and do a graceful restart of your mailer?

**Comment by andreoav** [comment] 2012-12-16 18:35
Ok, I think I'll try a different approach. I get this error only with this blocking pop, maybe using the normal lpop to send all emails and restart the worker periodically.

Thanks for your answer. 
Closing this issue since it's not related to Fuel Core.

**Comment by andreoav** [comment] 2012-12-17 17:49
After doing some research, I decided to do some tests using a different redis PHP client.
So I downloaded the Predis client change my mailer to use Predis instead of the core class.

I had the same error after 60 seconds. But I found a issue in the Predis repository saying that I should pass a parameter to the  constructor.

``` php
$redis = new \Predis\Client(array(
    'read_write_timeout' => 0
));
```

After this, everything works without error. No more error after 1 minute.
So I'm reopening this issue since I think it's a client bug instead of a redis-server issue.

**Comment by WanWizard** [comment] 2013-01-12 22:41
Looked into this, but this is very difficult to solve.

Since we're going to swap the current class for Predis in v2.0, perhaps you should just swap to Predis now. It's a Composer compliant package, so you can use it now without problems.

**Comment by andreoav** [comment] 2013-01-12 23:30
I've been using Predis since I reported this bug without problemas so far.
Thx.

**Comment by frankdejonge** [comment] 2013-04-26 11:19
Closing this since 2.0 will use Predis where this is handled, for 1.x usage we recommend using predis (trough composer, which makes it as easy as pie).

**Closed as completed by frankdejonge** 2013-04-26 11:19 UTC
Labels: Bug, Pending, Address in 2.0

**Comment by kitabatake** [comment] 2019-04-22 07:45
It can be reproduced by
```
1. set redis server timeout config
2. run some session used(like Auth::check()) fuel task it over timeout
```
