### ISSUE TITLE
Theme and Asset : "src" attribute on Windows environment

### ISSUE THREAD

**Issue by lvancrayelynghe** [fuel/core#1012] opened 2012-06-11 18:16 UTC
I tried to use "Theme::instance()->asset->css('bootstrap.min.css');" with this theme configuration :

``` php
return array(
    'active' => 'default',
    'fallback' => 'default',
    'paths' => array(DOCROOT.'themes'),
    'assets_folder' => 'assets',
    'view_ext' => '.php',
    'require_info_file' => false,
    'info_file_name' => 'themeinfo.php',
);
```

Returns :

``` html
<link type="text/css" rel="stylesheet" href="http://localhost/public/themes\default\assets/css/bootstrap.min.css?1338573966" />
```

Instead of :

``` html
<link type="text/css" rel="stylesheet" href="http://localhost/public/themes/default/assets/css/bootstrap.min.css?1338573966" />
```

Corrected by replacing in "fuel/core/classes/assets/instance.php", line 244 :

``` php
$attr['href'] = $file;
```

By :

``` php
$attr['href'] = str_replace('\\', '/', $file);
```

Same for js, line 254 and img, line 259. 

Don't really now if it's the best way, but it works.

**Comment by WanWizard** [comment] 2012-06-12 09:48
This is not the solution, the issue is caused I believe by the theme class when it determines the path to the theme assets.

I don't have Windows, so I can't test it. Can you add 

```
$theme['asset_path'] = str_replace(DS, '/', $theme['asset_path']);
```

to the theme class, in the create_theme_array() method, just before `return $theme` and see if this solves it?

**Comment by lvancrayelynghe** [comment] 2012-06-12 19:15
I tried (after removing my str_replace()), but it returns :

``` html
<link type="text/css" rel="stylesheet" href="http://localhost/public/D:/WAMP/www/public/themes/default/assets/css/bootstrap.min.css?1338573966" />
```

**Comment by lvancrayelynghe** [comment] 2012-06-12 19:55
Ok, I think I found why it don't work. If you look here :
https://github.com/fuel/core/blob/1.3/develop/classes/asset/instance.php#L404

``` php
strpos($file, DOCROOT) === 0 and $file = substr($file, strlen(DOCROOT));
```

The strpos() test will fail, because '\' are replaced by '/'

``` php
D:/WAMP/www/public/themes/default/assets/css/bootstrap.min.css
```

``` php
D:\WAMP\www\public\
```

If I try :

``` php
strpos($file, str_replace('\\', '/', DOCROOT)) === 0 and $file = substr($file, strlen(DOCROOT));
```

It works

**Comment by WanWizard** [comment] 2012-06-13 18:56
@Benoth, that result is odd because the line you needed to add doesn't change the path. You haven't assigned it to asset_base by any chance? Because the backslashes in the path are correctly changed to forward slashes.

It is not a bug in the Asset class, so it should not be fixed there. This is a hack that will not be implemented, you should fix the bug, not add a workaround.

**Comment by lvancrayelynghe** [comment] 2012-06-13 20:46
I restored the core to be sure and re-add your line. Same problem.

It does change the path, if i make a "vardump($theme);" without your suggestion here : https://github.com/fuel/core/blob/1.3/develop/classes/theme.php#L792 returns :

``` php
array
  'name' => string 'default' (length=7)
  'path' => string 'D:\WAMP\www\public\themes\default\' (length=34)
  'info' => 
    array
      empty
  'asset_path' => string 'D:\WAMP\www\public\themes\default\assets/' (length=41)
  'asset_base' => string 'themes/default/assets/' (length=22)
```

If i add "$theme['asset_path'] = str_replace(DS, '/', $theme['asset_path']);" just before, it returns :

``` php
array
  'name' => string 'default' (length=7)
  'path' => string 'D:\WAMP\www\public\themes\default\' (length=34)
  'info' => 
    array
      empty
  'asset_path' => string 'D:/WAMP/www/public/themes/default/assets/' (length=41)
  'asset_base' => string 'themes/default/assets/' (length=22)
```

Can't test anymore right now, but I will later

**Comment by WanWizard** [comment] 2012-06-13 20:55
What I find odd is that the "asset_base" is correctly determined as "themes/default/assets/". Which is used to construct the URL for the asset.

What puzzles me that somewhere the correct slashes are converted back to DS...

edit: you were on the right track, Theme doesn't pass asset_base to Asset, it recalculates it. Fix on the way.

**Closed as completed** 2012-06-13 21:23 UTC

**Comment by m4tthumphrey** [comment] 2012-07-04 21:45
This is causing me problems! The slashes for all asset types are doubling to <code>//</code>. I'm on Windows 7 using WAMP. I rolled back to the version before and all was fine again. Will look into this in more detail tomorrow.

I think it is to do with line 407. It should be: 

```
return preg_replace('#'.DS.'+#', '/', $file);
```

Can't really check now, will confirm tonight.

**Comment by WanWizard** [comment] 2012-07-05 13:55
That's not the solution, that's a workaround. The solution should not to have double slashes in the first place.

Some more debugging is needed, which is difficult as I don't have a Windows environment.

**Comment by WanWizard** [comment] 2012-07-05 14:24
Looking in the code: are you passing an asset in a folder to the request? Like '/this/folder/asset.jpg', which a leading slash?

If so, the code assumes that on Windows all directory separators are backslashes, also the ones in the asset file name that you request, not only in the asset path. After finding the file (where PHP ignores the separators), it will replace the DIRECTORY_SEPARATOR by a forward slash so it can be used in the src attribute. But it doesn't touch forward slashes already there, leaving you with two forward slashes.

**Comment by m4tthumphrey** [comment] 2012-07-05 15:06
It happens on ALL of my Asset::*() calls, CSS, JS, and images. Am calling CSS and JS like so:

```
Asset::css(array(
        'style.css'
    ), array(), 'css');

    Asset::js(array(
        'http://code.jquery.com/jquery-latest.min.js',
        'http://maps.googleapis.com/maps/api/js?sensor=false',
        'scripts.js'
    ), array(), 'scripts');
```

And images just <code>Asset::img('image.jpg')</code>.

I will test your update tonight.
