### ISSUE TITLE
Date class bug 

### ISSUE THREAD

**Issue by huzzi** [fuel/core#309] opened 2011-07-26 09:04 UTC
The Date::time_ago() seems to break (timing out) if your timestamp variable passed to it is empty.

ErrorException [ Error ]: Maximum execution time of 30 seconds exceeded

On line 182 where it's checking for if it's null also need to check if the value is empty.
if ($timestamp === null || $timestamp =='')

**Comment by jschreuder** [comment] 2011-07-26 09:12
That addition is wrong `$timestamp == ''` will also match 0 which is a valid timestamp. A better solution might be to cast to int when not null.

Also I have to see if this problem really exists, because you don't describe why it would occur.

**Comment by huzzi** [comment] 2011-07-26 10:04
I was passing the the $timestamp from the database which contained empty string.

**Comment by jschreuder** [comment] 2011-07-26 10:10
That's not what I meant, why would an empty string cause the problem?

From a quick look I don't think that an empty string is the actual probem, the problem would have to be in the for loop (there's no other way this would go on forever). And while it might occur because of an empty input, that doesn't mean the empty input is the problem - the problem is most likely somewhere in the logic. Thus the logic should be fixed, the input is secundary.

**Comment by huzzi** [comment] 2011-07-26 10:16
yes, you're right.

**Closed as completed** 2011-07-28 14:52 UTC
Labels: Bug
