### ISSUE TITLE
Fieldset In Fieldset Template Generation problem

### ISSUE THREAD

**Issue by CoolGoose** [fuel/core#694] opened 2011-11-28 14:50 UTC
If you have a fieldset into another fieldset the error template for the field from the build method doesn't get correctly populated since the validation class returns that field to be invalid after the fieldset processing is complete.

**Comment by dhrrgn** [comment] 2011-12-09 00:14
Can you provide the code to reproduce this please?

**Comment by CoolGoose** [comment] 2011-12-11 09:03
Form: http://scrp.at/aPX
Config: http://scrp.at/aPY

**Comment by dhrrgn** [comment] 2011-12-19 06:04
Thanks will take a look soon.  Unless @jschreuder knows exactly what the issue is.

**Comment by jschreuder** [comment] 2011-12-19 13:14
@CoolGoose You've shown how you generate the form, but without the important part: how do you show the errors, an example of your output and what it should have been. Probably there's something wrong in a method that should collect from all the sub-fieldsets as well and doesn't. Without the info it's hard to replicate, especially if I don't know what exactly is wrong ("correctly populated" is a very subjective non-specific issue)

**Comment by CoolGoose** [comment] 2011-12-19 13:56
The thing is that it's not showing the error class on the input fields from the subfieldsets.

It validates the inputs properly, but the template used for generating the form is being called before the actual validation happens, so it doesn't show the 'error' class on the div for the subfieldsets.

**Comment by jschreuder** [comment] 2011-12-19 14:11
> but the template used for generating the form is being called before the actual validation happens

I'm not sure how that's possible... the form field html is only generated when it must, at the very last moment when you echo it. That should be well after the validation took place.

From a quick look through the code it looks like the problem is that each Fieldset instance has its own Validation instance. Validation was performed by the Validation instance belonging to the parent Fieldset, but when the Fieldset_Field instance is being build it takes its error status from the Validation instance that belonged to the child Fieldset to which the Field belongs - which isn't the same Validation instance that determined the error. Thus no error is detected and the error class isn't assigned.

**Comment by CoolGoose** [comment] 2011-12-19 14:27
That's pretty much it.

Do or can I overwrite each validation instance to only use the main one or ? :)

**Comment by jschreuder** [comment] 2011-12-19 14:41
I don't think so, each Fieldset instance is a tripod with Form & Validation objects allowing specific settings per fieldset. Part of the problem is that Validation wasn't originally written with nested fieldsets in mind. And I'm not sure if the current solution is even the most optimal one, this needs some further looking into before it can be fully solved.

**Comment by CoolGoose** [comment] 2011-12-19 15:07
Gotcha ;) .

Good to know it's somewhat of a bug :P . On track for 1.2 / 2.0 ? :D

**Comment by jschreuder** [comment] 2011-12-19 15:38
For 2.0 I'll probably do a full rewrite of the whole thing, but that's far into the future.

No planning at this point from me, I'm swamped at work for the next few weeks (including the holidays).

**Comment by WanWizard** [comment] 2012-01-12 09:31
Marking this as feature for 2.0.

**Comment by WanWizard** [comment] 2012-11-01 15:39
Afaik this issue was fixed by PR #1140. If not, let me know and I'll reopen the issue.

**Closed as completed by WanWizard** 2012-11-01 15:39 UTC
Labels: Bug, Feature
