### ISSUE TITLE
Output Encoding is converting objects to arrays

### ISSUE THREAD

**Issue by jeffutter** [fuel/core#53] opened 2011-04-20 15:01 UTC
It seems that if you pass an object to a view using output encoding it any related objects are converted to arrays. This causes a problem in a situation like:

$this->template->mustache_templates['m_checkout_payments'] = View::factory('mustache/checkout/payments')
            ->set('job', $job);

 $this->template->mustache_templates['m_checkout_charges'] = View::factory('mustache/checkout/charges')
            ->set('job', $job);

You can see the dump between the 2 job variables in the scrp below.

http://scrp.at/T9

The $job variables should not be different between the 2 times they are used. If I set output-encoding to false  it works fine.

**Comment by jschreuder** [comment] 2011-04-20 15:15
Tracked it down, it's not a problem with the output encoding as I first thought. It's caused by the new iterable implementation, that returns arrays instead of instances.

**Comment by jschreuder** [comment] 2011-04-20 15:22
Fixed in the Orm.

**Closed as completed by jschreuder** 2011-04-20 15:22 UTC
Labels: Bug
