### ISSUE TITLE
Extension bug

### ISSUE THREAD

**Issue by jemmy** [fuel/core#1292] opened 2013-01-22 08:35 UTC
Route
data/xml/(:any)
URL
/data/xml/content.xml

Bag action set to 'xm'

**Comment by WanWizard** [comment] 2013-01-22 11:23
What do you exactly mean?

**Comment by jemmy** [comment] 2013-01-22 16:04
If the link type /data/xml/content.xml be carrying action Controller_Data->action_xm()
instead Controller_Data->action_xml()

**Comment by WanWizard** [comment] 2013-01-22 16:37
Can you post your defined routes.php? By default, extensions are ignored in a FuelPHP application.

**Comment by jemmy** [comment] 2013-01-23 10:48
$strip_extension = true; 
Change line 180 in route.php
strpos($uri, $ext = \Input::extension()) === false or $uri = substr($uri, 0, -(strlen($ext)+1));
to 
strpos($uri, $ext = '.' . \Input::extension()) === false or $uri = substr($uri, 0, -(strlen($ext)+1));

**Comment by WanWizard** [comment] 2013-01-23 13:41
I can not reproduce this.

If strip extension is true (and it is by default), and I use a URI like "/this/that/something.html", after line 180, $ext contains "html", and $uri contains "this/that/something", which is correct.

If you add the dot, like you propose, you don't change anything to $uri, only to $ext, but that isn't used anywhere in that method (only for stripping the extension from the url on that line). So what do you want to achieve whis this? What does it solve?

**Comment by WanWizard** [comment] 2013-01-23 13:43
If you have defined a route with "/data/xml/content.xml' as route target, that target isn't processed in any way, and the original URI (with or without extension) isn't used in the routing process anymore. So I think you have an entirely different issue.

**Comment by jemmy** [comment] 2013-01-23 14:31
url /this/that/something.that
The expansion coincides with action that == that

strpos($uri, 'that') == 6 
strpos($uri, '.that') == 20

**Comment by hackoh** [comment] 2013-02-13 09:45
@WanWizard 
I think this issue is very critical.
If the any of the segments contain the extension string, then this problem always occurs.
For example,
- http://localhost/data/html/test.html
- http://localhost/images/png-images/sample.png

**Comment by WanWizard** [comment] 2013-02-13 10:02
What exactly is the problem with this?

It gets the extension, and strips it of the end. It doesn't care that the string is also in the middle of the URL?

When I test with "http://localhost/images/png-images/sample.png", it gives me "http://localhost/images/png-images/sample" as URI, and "png" as extension. Like it should...

**Comment by hackoh** [comment] 2013-02-13 10:06
Ah, try this.

``` php
// routes.php
return array(
    '_root_'  => 'welcome/index',  // The default route
    '_404_'   => 'welcome/404',    // The main 404 route
    'data/xml/(:any)' => 'data/xml/$1',
    'images/png-images/(:any)' => 'data/xml/$1', 
    'hello(/:name)?' => array('welcome/hello', 'name' => 'hello'),
);
```

``` php
// data.php (controller)
    public function action_xml($foo)
    {
        Debug::dump($foo); // incorrect result.
        exit();
    }

```

**Comment by WanWizard** [comment] 2013-02-13 10:28
That debug displays "sample" here with the above test URL. Which seems correct to me? Tried with multiple params as well, but that goes well too?

**Comment by WanWizard** [comment] 2013-02-13 10:33
I can't see what will go wrong. The code in Route::matched doesn't do anything with the returned strpos() position, it isn't even assigned to a variable.

Where it could go wrong is when you have a URL like

`http://localhost/images/png-images/sample.jpg`

and Input::extension() would return 'png', because then it would think the URI has an extension and it will strip ".jpg" instead. But that can not happen, Input::extension() always returns the same URI extension as present in the URI.

**Comment by hackoh** [comment] 2013-02-13 10:55
Can you try this?

``` php
// data.php (controller)
    public function action_xml($foo)
    {
        Debug::dump(Input::uri());
        Debug::dump($foo); // 'sample'
        exit();
    }
```

Maybe, you get '/images/png-images/sample.png', don't you?
In my case, I got '/images/png-images/sample'.
Input::uri() code is complicated, so I do not understand a reason. 
(It seems that environment is related)

I think, at the time of the 180th line of route.php, when the extension of $uri is already excised, it falls into our condition.

**Comment by hackoh** [comment] 2013-02-13 11:07
Ah, no no, my explanation was wrong. 
In my case,

``` php
// route.php Line 180
                if ($this->strip_extension)
                {
                    Debug::dump($uri); // 'images/png-images/sample'
                    strpos($uri, $ext = \Input::extension()) === false or $uri = substr($uri, 0, -(strlen($ext)+1));
                }
```

So strpos() catches 'png' in $uri.

**Comment by hackoh** [comment] 2013-02-13 11:09
Why is $uri `'images/png-images/sample'` ?
I don't know that..

Anyhow, if the line means 'to strip extension', 
and if $uri contains a Input::extension() string and a extension already stripped, 
then $uri brings a result which is not expected.

**Comment by WanWizard** [comment] 2013-02-13 11:52
Ah, the problem is the other way around?

Your URI has no extension? As in "http://localhost/images/png-images/sample"? Why does Input::extension() return 'png' then? It should return false (the URI does not have an extension), and $uri will not be altered in Route::matched.

**Comment by kenjis** [comment] 2013-02-13 11:52
route.php:

``` php
<?php
return array(
    '_root_'  => 'welcome/index',  // The default route
    '_404_'   => 'welcome/404',    // The main 404 route
    'images/png-images/(:any)' => 'data/xml/$1',
);
```

data.php:

``` php
<?php
class Controller_Data extends Controller
{
    public function action_xml($foo)
    {
        Debug::dump(Input::uri());
        Debug::dump($foo);
        exit();
    }
}
```

URL: `http://localhost/fuel/images/png-images/sample.png`

Result:

```
APPPATH/classes/controller/data.php @ line: 6
Variable #1:
  (String): "/images/png-images/sample" (25 characters)

APPPATH/classes/controller/data.php @ line: 7
Variable #1:
  (String): "sa" (2 characters)
```

**Comment by WanWizard** [comment] 2013-02-13 11:54
Scratch that. I'm beginning to understand what you write.

Ths issue seems to be that in Router::matched(), the $uri arrives with a stripped extension, due to the route that is processed?

**Comment by hackoh** [comment] 2013-02-13 12:32
> Ths issue seems to be that in Router::matched(), the $uri arrives with a stripped extension, due to the route that is processed?

If it is so, the code should be below.

``` php
                if ($this->strip_extension)
                {
                    $uri = substr($uri, 0, -(strlen($ext)+1));
                }
```

But it is not.
The current code assumes that $uri is made into nakedness and arrives. doesn't it?

**Closed as completed** 2013-02-13 12:34 UTC
Labels: Bug, Awaiting feedback, Pending

**Comment by WanWizard** [comment] 2013-02-13 12:36
No, not exactly.

The issue is that "strip_extension" is a local parameter of the Route object. So it can be that "strip_extension" in the config is set to false, but the object is created with a strip_extension set to true. So it also needs a check if there actually is an extension to strip. Which I just added.

**Comment by hackoh** [comment] 2013-02-13 12:51
Great fix.
I got correct results.

**Comment by WanWizard** [comment] 2013-02-13 13:15
Cool. One more problem solved then. Thanks for the feedback.

**Comment by kenjis** [comment] 2013-02-13 23:10
Good job!

Please close https://github.com/fuel/core/pull/1325
