### ISSUE TITLE
Problem on Form::label()

### ISSUE THREAD

**Issue by keech** [fuel/core#1759] opened 2014-08-20 15:20 UTC
Even if I set config/form.php like below
`return array(
    'auto_id'  => false,
);`
and set second argument of Form::label(),  'for' attribute is not created.

I found the problem point.
![form_instance_label](https://cloud.githubusercontent.com/assets/6279099/3982929/2236b09a-287b-11e4-804f-de18940d15a2.png)

I hope your solution to this problem.

**Comment by WanWizard** [comment] 2014-08-21 16:10
And why is that the problem point?

The label() method hasn't got a clue for which input field you're generating the label. So if you enable auto_id, the field name is generated and can therefore be added, but if it is disabled, there is no why to guess what the contents of "for" should be...

**Comment by kenjis** [comment] 2014-08-22 01:56
The `if` statement seems okay to me.

The problem is `$id` is not used?

**Comment by keech** [comment] 2014-08-22 03:38
I'm sorry I should have let you know my situation.

This is an example which let me know this problem.

---

IF------------------
■View

```
$label = 'label';
$id = 'id';
echo \Form::label($label, $id);
```

■fuel/app/config/form.php

```
return array(
    'auto_id' => false,
);
```

THEN------------------
■html
`<label>label</label>`

---

I think it should be
■html
`<label for="id">label</label>`

But 
■fuel/core/classes/form/instance.php
`if (empty($attributes['for']) and $this->get_config('auto_id', false) == true)`
makes it impossible, I think.

How do you think?

**Comment by kenjis** [comment] 2014-08-22 07:41
I sent PR of my fix: #1761

But I don't know current `auto_id` spec for label() method is good or not.
If `auto_id` is true (default), we still have to set `id`. What is auto?

**Comment by WanWizard** [comment] 2014-08-22 07:54
When auto_id is true, id's are generated based on the prefix and id, as you can see in this bit of code. It's a fieldset feature, and in this method, it makes sure the id is the same as the one generated for the input tag. 

When you call Form::label() manually, it isn't really relevant, you have to pass the id in order to get a 'for' attribute. So I think it should be:

```
if (empty($attributes['for']) and ! empty($id))
{
    if ($this->get_config('auto_id', false) == true))
    {
        $attributes['for'] = $this->get_config('auto_id_prefix', 'form_').$id;
    }
    else
    {
        $attributes['for'] = $id;
    }
}
```

**Comment by kenjis** [comment] 2014-08-22 08:20
Okay. 
It is cleaner logic. I fixed my PR.

**Comment by keech** [comment] 2014-08-22 08:24
Getting better!!
Thx!!

**Comment by WanWizard** [comment] 2014-08-22 16:05
PR merged.

**Closed as completed by WanWizard** 2014-08-22 16:05 UTC
