### ISSUE TITLE
Dual join error

### ISSUE THREAD

**Issue by flipzoom** [fuel/core#1157] opened 2012-09-28 22:06 UTC
Hello, 

I think in the current version 1.3 is an error in the DB Query Builder at the joins. If I construct a query with a join()->on() and with a join() only, the SQL query fails because the second query generated automaticly ->on() with no parameters. Here is an example: 

``` php
\DB::select('*')
    ->from('routes')
        ->join('meta','LEFT')
        ->on('meta.route_id', '=', 'routes.id')
        ->join('frontend_settings', 'INNER')
    ->where('routes.entry_point', '=', '1')
    ->limit(1)
    ->execute();
```

And the Error with the generated SQL: 

Fuel\Core\Database_Exception [ 1064 ]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') WHERE `s3_routes`.`entry_point` = '1' LIMIT 1' at line 1 [ SELECT \* FROM `s3_routes` LEFT JOIN `s3_meta` ON (`s3_meta`.`route_id` = `s3_routes`.`id`) INNER JOIN `s3_frontend_settings` ON () WHERE `s3_routes`.`entry_point` = '1' LIMIT 1 ]

UPDATE:

I have now tested the query without the Query Builder and the additional on-condition (following code) and it works fine.

``` php
\DB::query("SELECT * FROM `s3_routes` LEFT JOIN `s3_meta` ON (`s3_meta`.`route_id` = `s3_routes`.`id`) INNER JOIN `s3_frontend_settings` WHERE `s3_routes`.`entry_point` = '1' LIMIT 1", \DB::SELECT)->execute();
```

**Comment by WanWizard** [comment] 2012-10-23 19:12
@FrenkyNet is this case covered in Cabinet?

**Comment by WanWizard** [comment] 2012-10-27 10:01
Duplicate of #1130

**Closed as completed by WanWizard** 2012-10-27 10:01 UTC
