### ISSUE TITLE
Oil refine broken - could not find any class after new Finder was added

### ISSUE THREAD

**Issue by darklow** [fuel/core#567] opened 2011-10-11 12:12 UTC
After updated core and oil package to "1.1/develop" tasks stoped working.
I guess problem appeared after new finder class was edded.

> php oil r robots
> Error: Task "robots" does not exist. Did you mean "robots"?

If i remove ucfirst() in this line 37 in oil/classes/refine.php - then it works. 

``` php
$task = ucfirst(strtolower($task));
```

Something to do with case sensitivity i just don't know is it refine.php or Finder class problem.

**Comment by crynobone** [comment] 2011-10-11 13:42
Should be Finder class problem...

**Comment by crynobone** [comment] 2011-10-11 14:38
Can't reproduce this in my environment, Zend Server CE running on Mac

**Comment by darklow** [comment] 2011-10-11 18:38
Just created totally new and clean source using:
git clone -b "1.1/develop" --recursive git://github.com/fuel/fuel.git

And same error: php oil r robots
Error: Task "robots" does not exist. Did you mean "robots"?

Debian GNU/Linux 6.0.2, PHP 5.3.5 (cli)

**Comment by WanWizard** [comment] 2011-10-11 20:57
Afaik the convention is that filenames are lowercase. So I would say it's a refine problem, it shouldn't do a ucfirst(). The ucfirst() should be in line 67, as the class name does start with a capital letter.

**Comment by WanWizard** [comment] 2011-10-11 21:06
Fixed in oil repo commit https://github.com/fuel/oil/commit/8555d3d6e928ac83f671c87bb14d5bb16e435c9f

**Closed as completed by WanWizard** 2011-10-11 21:06 UTC
