### ISSUE TITLE
Module cannot be extended and replaced

### ISSUE THREAD

**Issue by sagikazarmark** [fuel/core#1750] opened 2014-08-05 22:08 UTC
Because of [this](https://github.com/fuel/core/blob/1.8/develop/classes/finder.php#L320) line `Module` class is loaded before always_load, so it is a bit hard to extend and replace it. I don't really know how is this possible, but according to [backtrace](http://bin.fuelphp.com/snippet/view/Hi) it is loaded there.

**Comment by sagikazarmark** [comment] 2014-08-05 22:11
Well, it is not just oil console. It is a recent change which makes it impossible to replace Module class from a package.

**Comment by sagikazarmark** [comment] 2014-08-06 11:23
IMO this breaks BC

**Comment by WanWizard** [comment] 2014-08-06 11:41
The finder is called for the first time to load the config, which indeed means the Module and Package classes are loaded at that point.

I'm always open for better solutions.

The problem in the finder is that when packages or modules are loaded, the cache id should change, to avoid having incorrect data returned when you load a file. 

Say you load a config file called "abc", it is found in app/config. loaded and cached. Next you load Package "xyz", which also contains a config file "abc". If you now load config file "abc" again, you would expect the package config and the app config to be merged. This didn't happen before, because the cause id was generated on search value ("abc") so the second load only loaded the app config and not the package config.

So you need a cache key that is different for any combination of modules and packages loaded using a predicatable algorithm (otherwise the cache would be useless).

You can still extend by the way, but you'll have to use Package::load() in your app bootstrap, after you have added your custom class to the autoloader, and before Fuel::init() is called.

**Comment by sagikazarmark** [comment] 2014-08-06 11:50
I know I can extend from app, but this is what I wanted to avoid, since it is not an app based replacement, but a package.

What do you think about a solution where first there is a check whether always_load is run or not. If yes then the finder can use the Module and Package classes. Until then both returns an empty array, so it is just not necessary to use them before always_load.

**Comment by WanWizard** [comment] 2014-08-06 11:57
That is not what I wrote.

Instead of loading your package (which does the extending) in the always_load, you can load the package using `Package::load('packagename');` in your app bootstrap. This only works for extending Module, you can't extend Package that way (obviously).

**Comment by WanWizard** [comment] 2014-08-06 12:00
p.s. I'm not in favour of creating a huge dependency mess between Fuel::init, the Finder, and the Module and Package classes.

Perhaps it's a better solution to check in the finder for `class_exists('Module', false)`, and only add `Module::loaded()` to the cache key when that returns true. Because as long as the class isn't loaded, there can't be a module present. Same is true for Package.

**Comment by sagikazarmark** [comment] 2014-08-06 12:07
I was thinking about a Fuel::$loaded variable (like $env), but your solution is better.

**Closed as completed** 2014-08-06 14:08 UTC
