### ISSUE TITLE
Latest 1.1 develop core has broken Request::active()

### ISSUE THREAD

**Issue by phil-lavin** [fuel/core#418] opened 2011-08-23 08:25 UTC
Request::active() returns null. Request::main() returns the main request. The active request is the main, in this instance.

**Comment by andrewwheal** [comment] 2011-08-23 10:14
This could be related to this commit: https://github.com/fuel/core/commit/1566fdd826ecbc4e01e71c183c4655db33911b84

That commit caused issues where our Admin module used Request::factory($url) for the functionality on a Request object but does not execute it.

**Comment by jschreuder** [comment] 2011-08-23 10:28
How and where do you use this? Is it during normal execution or outside of it? Request::active() used to return a request even after execution was done, this has been undone. Also Request instances are now only marked as active during their execution, not before or after.

**Comment by phil-lavin** [comment] 2011-08-23 10:31
This is used during normal execution of the main request to a module. In my case, I am just trying to reference \Request::active() which is returning null. \Request::main() works but I wish to use the module in both a HMVC context as a widget and when requested as the main request - hence using active().

**Comment by jschreuder** [comment] 2011-08-23 10:33
I'm not really sure how that could happen: https://github.com/fuel/core/blob/1.1%2Fdevelop/classes/request.php#L316 - that shouldn't be possible to fail.

**Comment by jschreuder** [comment] 2011-08-29 00:10
I tested this a bit and went through the code, I have no clue how this is possible and can't replicate the issue. I'll need some more info or I'll close it as invalid.

**Comment by phil-lavin** [comment] 2011-08-30 07:36
I'll make attempts to work out what is causing this.

**Comment by billmn** [comment] 2011-08-30 08:24
It works for me...

**Comment by WanWizard** [comment] 2011-08-31 12:40
Can't reproduce this either.

```
\Debug::dump( \Request::active() )
```

from a method inside an HMVC request dumps the correct request object.

**Comment by jschreuder** [comment] 2011-08-31 15:06
@phil-lavin I found your issue as I experienced it myself just now in a View. This is because Request::active() no longer refers to any request once the controller is done, and the output is only rendered only once the Request is done.

While this might be as simple as to put it back the way it was (the last Request stays active even when it's done), that doesn't solve anything as any usages in a View inside an Hmvc call would still refer to the wrong Request (the last active instead of their own). Gotta think about this...

**Comment by phil-lavin** [comment] 2011-08-31 15:14
I should probably have mentioned it's referenced from a view - sorry. Glad you've found it.

Phil

**Comment by WanWizard** [comment] 2011-08-31 15:48
This needs to be looked at in a broader context, as due to lazy rendering of the view, all concept of context is lost.

We had the same issue with find_file() paths, for which a solution is currently hacked into the View and Fuel classes.

Perhaps we need to store the active request as a property of the view, and use that when rendering the view to provide the correct context?

**Comment by jschreuder** [comment] 2011-08-31 15:50
> Perhaps we need to store the active request as a property of the view, and use that when rendering the view to provide the correct context?

That might work pretty well actually, it keeps the JIT rendering which is good while also mainting proper context.

**Closed as completed** 2011-08-31 17:14 UTC
Labels: Awaiting feedback
