### ISSUE TITLE
Uri Class weird behaviour

### ISSUE THREAD

**Issue by acstll** [fuel/core#307] opened 2011-07-26 06:10 UTC
hello everyone,

Uri::segment is returning empty when there's a number after a colon [:] on the first segment.

For example, this will return empty:

domain.com/pag:2

But this will not:

domain.com/pag:something

It works if it's on the second segment, like this:

domain.com/some:thing/pag:2

This is only happening on the server (PRODUCTION), 
not locally (DEVELOPMENT), although the application is exactly the same.

You can try it yourself live at http://fuel.8302.net
The problem arises with sorting and pages.
Uri::segment var_dumps at the top for you to see...

**Comment by dhrrgn** [comment] 2011-07-26 13:19
I have figured out why this is happening...now I just need to figure out how to fix it.  The problem is with the router/route classes.  It is interpreting the colon in the segment as a named parameter which is screwing everything up.

I will update when it is fixed.  I would suggest just not using the colon for now.  Why not just do domain.com/2 or whatever?

**Comment by acstll** [comment] 2011-07-26 14:51
No problem, I'll use slashes. And use this function:
(I just like the semantics of the colon)

```
private function set_uri_data()
{
    $segments = Uri::segments();

    if ( ! empty($segments[0]))
    {
        foreach ($this->uri_data as $key => $value)
        {
            if ($i = array_search($key, $segments) or $i === 0)
            {
                $i += 1;
                if ($key === 'tags') 
                    $this->uri_data[$key] = array_filter(explode($this->tag_separator, $segments[$i]));
                else $this->uri_data[$key] = $segments[$i];
            }
        }       
    }
}
```

But I'm missing the CI $this->uri->uri_to_assoc(n) function, which I try to replicate with that above.

**Comment by dhrrgn** [comment] 2011-07-26 22:45
You can use this function to emulate the uri_to_assoc() function:

```
function uri_to_assoc()
{
    $arr = Uri::segments();
    if (($count = count($arr)) % 2 > 0)
    {
        return false;
    }
    $keys = $vals = array();

    for ($i = 0; $i < $count - 1; $i += 2)
    {
        $keys[] = array_shift($arr);
        $vals[] = array_shift($arr);
    }
    return array_combine($keys, $vals);
}
```

It will return what you are looking for.  This will be going into core.

**Comment by dhrrgn** [comment] 2011-07-26 23:20
I just committed a change to the Arr class and the Uri class so there is now a Uri::to_assoc() method which does what you want.  If you pull from the develop branch you will get it.

I am still looking into the original issue though.

**Comment by acstll** [comment] 2011-07-27 06:21
Thank you, Dan.

**Comment by dhrrgn** [comment] 2011-07-29 11:20
I am going to have to push this to 1.0.x as there are a few other bugs I have noticed with the router when it comes to characters in the URI (the @ symbol completely breaks this for instance).

**Closed as completed** 2011-08-16 18:07 UTC
Labels: Bug
