### ISSUE TITLE
Str::truncate problem with $is_html

### ISSUE THREAD

**Issue by billmn** [fuel/core#434] opened 2011-08-30 17:58 UTC
Using Str::truncate function like :

<pre>Str::truncate('<p class="intro">You have successfully installed the Fuel PHP Framework.</p>', 15, ' ...', true);</pre>

I get :

<pre>
Notice!

ErrorException [ Notice ]: Uninitialized string offset: 0

COREPATH/classes/str.php @ line 47:

46: $tag = static::sub(strtok($match[0][0], " \t\n\r\0\x0B>"), 1);
47: if($tag[0] != '/')
48: {

</pre>

**Comment by WanWizard** [comment] 2011-09-02 15:22
I can not reproduce this on 1.1/develop.

**Comment by billmn** [comment] 2011-09-03 09:23
I've reinstalled the 1.1 develop and with a clean install the truncate() method give me the same error.

After some tests I noticed that the problem is related to the html tags in the string.

With this string :

<pre>$string = 'This &lt;b>Test message&lt;/b> can broke truncate &lt;i>method&lt;/i>, damn!';</pre>


1° Test - NO ERRORS:

<pre>
&lt;h2>&lt;?php echo Str::truncate($string, 4, ' ...', true); ?>&lt;/h2>
</pre>


2° Test - 1 ERROR:

<pre>
&lt;h2>&lt;?php echo Str::truncate($string, 6, ' ...', true); ?>&lt;/h2>
</pre>


3° Test - 2 ERRORS:

<pre>
&lt;h2>&lt;?php echo Str::truncate($string, 18, ' ...', true); ?>&lt;/h2>
</pre>

**Comment by billmn** [comment] 2011-09-15 10:30
Have you reproduced the error?

**Comment by jschreuder** [comment] 2011-09-15 11:22
@WanWizard has here: #462 but closed it as it duplicated this issue.

I also get the notices when running Unit tests.

**Comment by WanWizard** [comment] 2011-09-15 19:43
Yes, I have. As soon as you truncate in between the opening and closing tag, it creates a mess.

**Comment by WanWizard** [comment] 2011-10-18 08:12
Just tested this again, and it seems to be fixed along the way.
I'm closing this issue.

**Closed as completed by WanWizard** 2011-10-18 08:12 UTC
Labels: Bug, Already fixed
