### ISSUE TITLE
Fatal errors are not outputting

### ISSUE THREAD

**Issue by chrisharrison** [fuel/core#1377] opened 2013-03-13 13:13 UTC
I've been encountering an issue whereby any fatal errors that occur during execution are not displayed to the browser. In fact nothing is sent to the browser and it displays 324(net:ERR_EMPTY_RESPONSE). This happens across all browsers, it is not a browser issue.

This problem only surfaces on Mac OS X (I'm using Apache installed through XAMPP). When running the code on Windows or multiple Linux servers I get the correct output of the fatal error, displayed through the pretty Fuel error output page.

I can reproduce the issue by:

-Installing fresh copy of XAMPP on Mac OS X
-Installing fresh copy of Fuel 1.5.3
-In the action_index() of the welcome controller, placing a random PHP line with no semi-colon at the end (thus generating a fatal parse error)

I tried tracing the problem, and I got down to the register_shutdown_function() in fuel/core/bootstrap.php

If I exit() at the top of that function, or comment the whole function out completely, then the fatal error is outputted to the browser (sans Fuel's pretty error output display). I'm guessing that something is going wrong after that point (it goes on to call the Event class and the Error class) and because the code has already entered the shutdown function, the error is not outputting.

I tried repeating the same steps as above with Fuel 1.4 and the issue did NOT occur (i.e. the fatal error WAS shown as expected). The fact that Fuel 1.4 does not have a register_shutdown_function in its core bootstrap might be relevant?

I'm fairly certain this is a server configuration issue. As I stated, I can reproduce the error with fresh installs of the server and the Fuel code. But it's a problem because a) I can't find WHAT server config is causing the issue and b) it's the default server config on XAMPP on a Mac which I presume is a widely used setup.

As proof that I'm not the only one having this issue, this questioner seems to be encountering the same issue (not sure if he's using XAMPP, but he is using Mac OS):

http://stackoverflow.com/questions/12587680/php-error-handling-has-disappeared-since-upgrading-to-mountain-lion

I also posted an answer on that page which details a really hacky workaround solution that I came up with for this issue until I find out what the root cause is.

I recommend someone with more experience of PHP and the Fuel core code looks at this issue because I've got to the end of my talents in so far as identifying this issue.

**Comment by WanWizard** [comment] 2013-03-13 19:34
I don't have a Mac so I can't have a look, but one thing I can think of: is output compression enabled by default? 

And you're not having a second exception in the shutdown handler (easily tested by disabling the shutdown handler)?

**Comment by chrisharrison** [comment] 2013-03-14 04:01
I tired various combinations of the ob_callback setting in Fuel - it had no effect. But I haven't tried looking into it on the server level. I'll try that and get back to you.

**Comment by chrisharrison** [comment] 2013-03-14 09:30
If I comment out the call to Error::shutdown_handler(); I get the parse/fatal error outputted to the browser.

I checked the compression and zlib.output_compression is off

I checked the Apache log and I am getting:

exit signal Segmentation fault (11)

...at the point where I get the blank page inside the register_shutdown_function

Google says that this might have something to do with a badly written extension. Mac OS XAMPP does seem to have quite a few more PHP extensions enabled than the setups I have on Windows and Linux.

I'm going to attempt to run Fuel through the default Apache/PHP that comes with Mac OS to see if I still get the error, then compare the extensions that are installed...

**Comment by WanWizard** [comment] 2013-03-14 11:33
A segfault... Oops... 

Is APC of another accelerator running? Version mismatches on that level can have PHP code trigger a segfault.

**Comment by chrisharrison** [comment] 2013-03-14 12:18
Just checked, and fairly certain no accelerator was running in XAMPP or the default Mac OS Apache.

Just installed MAMP (which is PHP 5.4 instead of PHP 5.3) and it WORKS (i.e. fatal errors are outputted and logged).

I still don't know what configuration/module is causing this though.

One thing that I've seen come up in discussions about blank pages is zend multibyte. I can confirm the following settings for different Apache servers under Mac OS X:
- Setup | Zend Multibyte | Affected by this issue
- XAMPP | On | Yes
- Stock Apache | On | Yes
- MAMP | Off | No

No idea if zend multibyte has anything to do with it though.

I don't know if this issue is related in any way:
https://github.com/fuelphp-storage/kernel/issues/8

I'm guessing this problem hasn't come up before because of two major factors:
a) I bet a lot of people use MAMP, I try to avoid it because it's commercial
b) Perhaps a lot of people don't complain that their fatal errors aren't outputted, as long as everything works when they haven't got any fatal errors!

**Comment by WanWizard** [comment] 2013-03-14 13:13
c) a lot of people don't use a Mac. :smile:

**Comment by kenjis** [comment] 2013-03-14 13:22
How about XAMPP for Mac OS X 1.8.1-beta1?
http://www.apachefriends.org/en/xampp-beta.html

**Comment by chrisharrison** [comment] 2013-03-14 13:39
Just installed: XAMPP for Mac OS X 1.8.1-beta1.

It WORKS (i.e. shows and logs fatal errors).

If I switch back to my previous XAMPP (which is the latest stable 1.7.3) it does not work. And neither does the stock Apache server that comes with Mac OS X.

Interestingly zend.multibyte is OFF on the XAMPP beta. So a pattern is emerging. Of course it could be coincidental, I have no idea.

**Comment by chrisharrison** [comment] 2013-03-14 13:44
By the way, although 'zend.multibyte' is Off, a separate setting 'Zend Multibyte Support' reads: 'provided by mbstring', which none of the other Mac OS Apaches tested thus far has. They all say either 'Disabled' (MAMP - which is working) or 'Enabled' (the other - not working).

A Linux machine that I tested did have 'provided by mbstring'. That was also working.

The crucial setting seems to be 'zend.multibyte'. This is 'Off' on all working configs and 'On' in all non-working configs.

Again I don't know if this has any relevance to the issue.

**Comment by kenjis** [comment] 2013-03-14 22:03
It might be a bug in zend.multibyte code in PHP 5.3.

How about changing zend.multibyte to 'On' in php.ini on PHP 5.4 ?

**Comment by chrisharrison** [comment] 2013-03-15 05:18
In PHP 5.3 I **think** that would mean re-compiling PHP, but in 5.4 it is configuration option.

I set 'zend.multibyte' to 'On' (default is Off) in PHP 5.4.10 (provided by MAMP) and the issue did not occur. But under 'Zend Multibyte Support' it still said 'provided by mbstring'.

I couldn't find a way to stop it from being provided by mbstring, without recompiling PHP, which I really don't know how to do on a Mac.

**Comment by WanWizard** [comment] 2013-04-11 16:47
I'm stil wondering if the issue is the original error, or, given the fact that it happens in the shutdown event, a problem with a second exception in the shutdown event. Which might be caused by log class troubles which should be fixed now. Could you try again with an up to date 1.6/develop?

**Comment by chrisharrison** [comment] 2013-04-12 08:51
Just tried 1.6/develop in one of the environments affected by this issue (native Mac OS X Apache+PHP). Unfortunately, it is affected in exactly the same way.

**Comment by frankdejonge** [comment] 2013-04-26 11:24
@WanWizard didn't you fix this last week?

**Comment by WanWizard** [comment] 2013-04-26 11:26
@FrenkyNet The problerm here is a segfault in Apache on XAMPP, I wouldn't know how to fix it from within PHP...

**Comment by chrisharrison** [comment] 2013-04-26 11:33
@WanWizard Not meaning to contradict you but it's not just XAMPP. Also affected is the Apache bundled with Mac OS.

**Comment by WanWizard** [comment] 2013-04-27 22:02
Doesn't really matter. Problem is in the installation, which can't be fixed by the framework.

I run locally: `PHP 5.4.13 (cli) (built: Mar 14 2013 09:15:21)` on Linux.

My installation also says `Zend Multibyte Support => provided by mbstring`, but `zend.multibyte => Off => Off`.

If you disable 'zend.multibyte' in your php.ini, is the problem fixed then?

And something else you can try, if you leave it on, can you explicitly set:

```
zend.script_encoding = utf-8
mbstring.internal_encoding = utf-8 
```

and see if this solves it?

**Comment by WanWizard** [comment] 2013-09-06 06:05
no response.

**Closed as completed by WanWizard** 2013-09-06 06:05 UTC
Labels: Bug, Pending
